#!/bin/sh

VERSION=1.0
MINOR_VERSION=0

ORGANIZATION=novasto
PROJECT=recore
APPLICATION=front


# ローカルにコンテナイメージの作成
docker build -t $ORGANIZATION/$PROJECT.$APPLICATION:$VERSION.$MINOR_VERSION ./$VERSION/$APPLICATION

# VERSIONにlatestタグ追加
docker tag $ORGANIZATION/$PROJECT.$APPLICATION:$VERSION.$MINOR_VERSION $ORGANIZATION/$PROJECT.$APPLICATION:latest

# DockerHubにpush VERSION指定
docker push $ORGANIZATION/$PROJECT.$APPLICATION:$VERSION.$MINOR_VERSION
docker push $ORGANIZATION/$PROJECT.$APPLICATION:latest
